version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - ${HTTP_GATEWAY_PORT}:${HTTP_GATEWAY_PORT}
    networks:
      - info-querying-component
    env_file: .env.docker

  web_scraper:
    build:
      context: .
      dockerfile: ./web_scraper/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - info-querying-component
    env_file: .env.docker

  nlp:
    build:
      context: .
      dockerfile: ./nlp/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - info-querying-component
    env_file: .env.docker

  news_embedding:
    build:
      context: .
      dockerfile: ./news_embedding/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - info-querying-component
    env_file: .env.docker

  news_search:
    build:
      context: .
      dockerfile: ./news_search/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    networks:
      - info-querying-component
    env_file: .env.docker

  fact_querying:
    build:
      context: .
      dockerfile: ./fact_querying/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - info-querying-component
    env_file: .env.docker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - info-querying-component

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 29092:29092
    networks:
      - info-querying-component
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - 29200:9200
    networks:
      - info-querying-component
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_HTTP_AUTH_PASSWORD}
    env_file: .env.docker
    healthcheck:
      test: "curl --silent -ku 'admin:admin' https://opensearch:9200 >/dev/null || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  info-querying-component:
    driver: bridge
